version: "3.9"

services:
  sensor:
    build: sensor
    depends_on:
      - controller
    environment:
      - CONTROLLER_URL=http://controller:8000/sensor-data/
      - RPS=30

  controller:
    build: controller


  manipulator:
    build: manipulator